export default {
  ROOT: '/',
  LOGIN: '/login',
  MAIN: '/main',
  PROJECTS: '/main/projects',
  PROFILE: '/main/profile',
  // SEARCH_FULL_SCREEN: '/search/:imageId',
  // IMAGE_IN_ALBUM_FULL_SCREEN: '/u/:username/a/:albumId/p/:imageId',
  // IMAGE_FULL_SCREEN: '/u/:username/p/:imageId',
  // SOCIAL_ACCOUNTS: '/profile/social_accounts',
  // CHANGE_PASSWORD: '/profile/password_email',
  // PERSONAL_DETAILS: '/profile/personal_details',
  // BILLING: '/profile/account/billing',
  // UPGRADE: '/upgrade',
  // THRESHOLD_UPGRADE: '/threshold-upgrade',
  // PAYMENTINFO: '/profile/account/paymentinfo',
  // USER_PATH: '/u/:username',
  // EDITOR: '/editor',
  // EXPLORE: '/explore',
  // COPYRIGHT: '/copyright',
  // NEW_MIGRATION: '/new-experience',
  // LIVE_MIGRATION: '/live-migration',
  // SLIDESHOW: '/slideshow',
  // SLIDESHOW_ALBUM: '/slideshow/u/:username/a/:albumId',
  // SLIDESHOW_ALBUM_SHARED: '/shared/slideshow/u/:username/a/:albumId',
  // HOME_SAFE_IMAGES: '/home/save-images',
  // HOME_EMBED_PHOTOS: '/home/embed-photos',
  // HOME_TOP_QUALITY: '/home/top-quality',
  // HOME_MAKE_PHOTOS_BEST: '/home/make-photos-best',
  // HOME_SHARE_IMAGES: '/home/share-images',
  USER_HOME: (username: string) => `/u/${username}`,
  ALBUM_LINK: (username: string, albumId: string) => `/u/${username}/a/${albumId}`,
  IMAGE_IN_ALBUM_LINK: (username: string, albumId: string, imageId: string) =>
    `/u/${username}/a/${albumId}/p/${imageId}`,
  IMAGE_LINK: (username: string, imageId: string) => `/u/${username}/p/${imageId}`,
  FAQ: '/faq',
  ANY: '*'
};
